Feature/1314 add data element geographic coordinates
SanDiegoCountySheriff/Cal-RIPA pull request #653
Opened 2023-07-20 21:11 UTC by KHORCASH

2023-07-21 13:53 UTC, jacobkellas commented
@KHORCASH let's see if we can wire this up to use the phone's GPS.  I believe you had a branch that did something similar to this a year ago or so.

2023-07-21 13:54 UTC, jacobkellas commented
AB#2379

2023-07-24 19:16 UTC, KHORCASH commented
See: https://github.com/SanDiegoCountySheriff/Cal-RIPA/pull/653/commits/ca9aa5c905e51401c2471432396f411974ca98ee

Latest commit adds:
- RipaLocation async function to check for geo availability score, disables 'Current Location' button if availability score is > 200 (brought over from branch 1570)
- moved Lat and Long input text fields out of Other location option section and is now under block# and street
- Added index.js validation of coordinates from getCurrentLocation function to match RipaLocation lat and long validation rules. (allow max of 3 numbers after the decimal point)
- Added unit test for Geo availability function

2023-07-24 22:14 UTC, jacobkellas requested changes
Haven't pulled the branch yet to test, but just a few cosmetic changes.

2023-07-24 22:14 UTC, jacobkellas commented on UI/src/components/molecules/RipaLocation.vue
> +    // isGeolocationAvailable() {
Remove commented code

2023-07-24 22:14 UTC, jacobkellas commented on UI/src/components/molecules/RipaLocation.vue
> +    console.log('geoavail:', this.geolocationAvailable)
Remove console.log

2023-07-24 22:14 UTC, jacobkellas commented on UI/src/components/molecules/RipaLocation.vue
> +          console.log(accuracyScore)
Remove console.log

2023-07-24 22:14 UTC, jacobkellas commented on UI/src/store/index.js
> +                console.log(latDecimal)
Remove console.log

2023-07-26 14:26 UTC, jacobkellas requested changes

2023-07-26 14:26 UTC, jacobkellas commented on UI/src/components/molecules/RipaLocation.vue
> +    latitudeRules() {
Lat and Long rules don't seem to be working.  I'm getting the error message after clicking "current location"

2023-07-26 14:26 UTC, jacobkellas commented on UI/src/components/molecules/RipaLocation.vue
> +        <v-row no-gutters>
Let's discuss if this should be at the top.  Also when I click current location, the "more location options" switch turns off and hides the field.

2023-07-31 14:52 UTC, jacobkellas approved these changes

2023-07-31 14:54 UTC, jacobkellas commented
@KHORCASH actually this isn't quite done, I forgot about a couple bugs we found last week.  Let me see if I can compile a list and we'll go over this today.

2023-07-31 14:55 UTC, jacobkellas requested changes
Bug fixes

2023-07-31 16:07 UTC, jacobkellas approved these changes

2023-07-31 16:09 UTC, merged